### ISSUE TITLE
Incorrect Log in/out procedure can lead to panic if VoicemeeterRemote is created and dropped multiple times

### ISSUE THREAD

**Issue by not-holar** [Emilgardis/voicemeeter-sdk-rs#26]
I'm trying to make my program retry connecting to Voicemeeter every n seconds if it wasn't running right away by creating VoicemeeterRemote instances in a loop and ran into an issue where my program crashes with an Access Violation Exception.

Following the calltrace

![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/58831297/db2e587c-823f-4993-9f07-edd4b1d24ea1)

![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/58831297/36f804cb-b40e-4a68-8ff8-c4a50830f132)

![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/58831297/8d8cd6bc-1524-488d-b7e5-7180642ba4e6)

![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/58831297/76fbe2f1-8c1c-4060-be8c-6255ab0fc923)

leads me to believe that the following is the issue:

```rust
impl VoicemeeterRemote {
    #[tracing::instrument]
    pub fn new() -> Result<Self, InitializationError> {
        let raw = crate::get_voicemeeter_raw()?;
        let mut s = VoicemeeterRemote::from_raw(raw);   <-- struct always created here
        s.login()?;   <-- returns out of new() early with InitializationError, dropping the struct as it goes out of scope, drop() is called
        s.program = s.get_voicemeeter_type()?;
        Ok(s)
    }

    fn from_raw(raw: &'static crate::VoicemeeterRemoteRaw) -> VoicemeeterRemote {
        Self {
            raw,
            program: VoicemeeterApplication::Other,
        }
    }
}

impl Drop for VoicemeeterRemote {
    fn drop(&mut self) {
        let _ = self._logout();   <-- drop calls logout but it didn't log in successfully, so this causes an Access Violation
    }
}
```

**Comment by not-holar** [comment]
one thing to note though is that it doesn't cause an exception the first time, only on subsequent creations of the remote

**Comment by not-holar** [comment]
adding a simple is_logged_in boolean flag to the remote struct seems to have fixed the issue

**Comment by not-holar** [comment]
well, it no longer crashes but it still doesn't log in on subsequent attempts if voicemeeter wasn't open during the first one

**Comment by Emilgardis** [comment]
Thanks for the report! 

That's a fun bug, should be an easy fix using [ManuallyDrop](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html) inside `VoicemeeterRemote::new`

**Comment by not-holar** [comment]
Actually, per their documentation, the login process should work anyway, regardless if Voicemeeter is running or not
![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/58831297/d325aa4f-7391-4820-aa82-e2ccbd5fbd98)

**Comment by not-holar** [comment]
and by further debugging, these all happen in sequence:

```
Err(NotLaunched)  <- Result of login(), makes sense, Voicemeeter isn't launched
VBVMR_Logout result: 0  <- Result of the logout() immediately after
Err(LoginFailed)  <- 15s later, try to log in again, it returns -2 => Err(LoginError::LoginFailed) which according to your comments stands for "unexpected login (logout was expected before)"
```

So the API first says that it logged out successfully only to then say that you actually didn't log out and throw an exception when you attempt to log out again, weird stuff, and seems like it's the API itself

**Comment by Emilgardis** [comment]
aha, the assumptions done in `VoicemeeterRemote::new` are wrong.

What you're supposed to do is

1. Start program.
2. Call login
3. do client stuff, including reconnecting
4. logout on exit.

the login is not for the voicemeeter application, it's for the session with voicemeeterremote

To fix this there have to be some changes, I think the easiest is a `static VB_LOGGED_IN: std::sync::OnceLock`

the hard part then becomes how to have the program logout, I guess the easiest is to just not call logout and let the consumer handle it

see https://discord.com/channels/755690270795890739/780757656356782080/829656857408045096 (on VB-AUDIO discord)

**Comment by not-holar** [comment]
> the hard part then becomes how to have the program logout, I guess the easiest is to just not call logout and let the consumer handle it

Perhaps it should just come down to a change of documentation, to tell the user explicitly that they should hold the VoicemeeterRemote instance for the entire duration of the program and then has to be dropped at the end

**Comment by Emilgardis** [comment]
> The important thing is that the struct that logs out on drop is not clonable as that would allow any of the copies to log out prematurely

Yes, this is a good point, removing the drop impl is the simplest solution imo.

**Comment by Emilgardis** [comment]
Not logging out causes some funky behaviour with 
![image](https://github.com/Emilgardis/voicemeeter-sdk-rs/assets/1502855/48d0c2fb-0037-401b-b4fc-61ca69a4d8b5)
